name: Changelog
on: workflow_dispatch

jobs:
  changelog:
    name: Changelog Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
          token: ${{ secrets[format('{0}_PAT', github.actor)] }}

      - name: Import GPG config
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets[format('{0}_GPG_PRIVATE_KEY', github.actor)] }}
          passphrase: ${{ secrets[format('{0}_GPG_PASS_PHRASE', github.actor)] }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set git info
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm install --global yarn
          yarn global add auto-changelog@2.3.0

      - name: Generate changelog
        run: |
          yarn tags:update
          yarn changelog
          git commit -m "[BOT] Changelog has been updated"
          git verify-commit HEAD

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: master
          tags: false
          github_token: ${{ secrets[format('{0}_PAT', github.actor)] }}

      # - name: Notify
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: frontend
      #     SLACK_COLOR: green
      #     SLACK_USERNAME: Tailor
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN }}
      #     SLACK_TITLE: Changelog
      #     SLACK_MESSAGE: 'Changelog (full) has been just updated'
      #     MSG_MINIMAL: true
